[package]
name = "scaleapi-cli"
version = "0.1.0"
authors = ["nisseknudsen <nisse.knudsen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.15.3"
shellexpand = "2.0.0"
clap = "2.33.2"